# Generated by Django 5.1.6 on 2025-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_logo_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodepositofmoney',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€')], max_length=3),
        ),
        migrations.AlterField(
            model_name='portfolioticker',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€')], max_length=3),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='operation',
            field=models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente'), ('dividend', 'Dividende')], max_length=8),
        ),
        migrations.DeleteModel(
            name='PortfolioDividend',
        ),
    ]
